### ISSUE TITLE
Message bar above extensions panel does not appear when 'Check for updates' is actioned. 

### ISSUE THREAD

**Issue by RDL-github** [AddonLab/AiOS#82] opened 2015-08-08 15:32 UTC
AiOS  0.7.26 in FF39.0 on Win 7 x64.

The message bar above the extensions panel does not appear when 'Check for updates' is actioned. However, the action itself _is_ going on although, because the bar does not appear, the messages cannot be seen.

The icon for viewing the available updates list panel still appears, as usual, in the icon panel above the searchbar (and the extensions which have available updates still have the little 'Update available' message below the version number in the extensions panel entry). Thus I am still be able to see the list of available updates if there are any.

I have tested in a new, nearly unmodified, profile and this problem also occurs there so I strongly suspect that AiOS is responsible. This is not a killer bug but it is irritating.

Until there's a fix for it, I'm using a slightly inelegant circumvention:

I've added the following five lines to userChrome.css:
# updates-container {

display: -moz-box !important;
hidden: false !important;
min-height: 28.2px !important;
}

That makes the message bar visible _all_ the time and I see the messages changing when, as they should, they do.

VBRR!

**Comment by RDL-github** [comment] 2015-08-11 18:01
For me, this problem persists in Firefox 40.0 and I still need the added CSS to see the message bar (in its new position before the tools button).

However, _with_ that CSS, the message bar does appear but only when I actually activate the check for updates. That is presumably as it should be but requires my added CSS before it even begins to work.

Since I don't have a 'Close' button on the bar, it stays until another sidebar is displayed before again displaying add-ons.

**Comment by ingowennemaring** [comment] 2015-08-30 21:01
As always - thanks for reporting. :-) And of course I will work for a solution.

**Comment by ingowennemaring** [comment] 2015-09-20 22:56
Will be fixed in the next release. :-)

**Comment by RDL-github** [comment] 2015-10-06 18:19
Thanks for latest release (0.7.27). Unfortunately, it does not solve this problem for me so I have retained the CSS which I used to circumvent the problem before.

VBRR.

**Comment by ingowennemaring** [comment] 2015-10-09 22:53
It seems much more complicated than I thought. It worked for me on all systems, although I mainly tested on Mac OS X and Win10. First I wasn't able to reproduce this problem, but now, after some installations and uninstallations of extensions, I have the same problem. It seems to be weird, but of course I will check what's going on here.

**Comment by ingowennemaring** [comment] 2016-11-06 18:44
Fixed in the next release. :-)

**Closed by ingowennemaring** 2016-11-06 18:44 UTC
Labels: bug, enhancement

**Comment by RDL-github** [comment] 2016-11-07 00:12
Fixed for me by AiOS 0.7.31 in FF 49.0.2 x64 on Win10 (Anniv) x64 

I have removed the circumvention CSS code.
